### ISSUE TITLE
Sync doesn’t work if custom fields are present

### ISSUE THREAD

**Issue by silsha** [sbywater/django-asana#1]
If you have custom fields enabled for one of your projects, the `sync_from_asana` command will fail:

```
$ ./manage.py sync_from_asana -mx=Tag
[…]
django.core.exceptions.FieldError: Invalid field name(s) for model Project: 'custom_field_settings'.
```

**Comment by sbywater** [comment]
Thanks. This particular error is now fixed in v1.1.2, although I have not written full support for custom fields. That is awaiting https://github.com/Asana/python-asana/issues/77

**Comment by silsha** [comment]
Thank you! I can confirm this particular error gone in d938854729f04069fc70caf61fcc97eeb62a4164 using the untagged python-asana 0.8.0, but there is a new error:

```
django.core.exceptions.FieldError: Invalid field name(s) for model Task: 'custom_fields'.
```

**Comment by sbywater** [comment]
python-asana has release v0.8.0 so I have just pushed initial support for custom fields. I do not have a paid account for Asana, and they do not provide a testing sandbox, so I've based this support on their API documentation. If you are comfortable using the stable tip of django-asana and letting me know if there are any issues, I would be glad to hear of it. If it works for you, I'll tag and release this version.

**Comment by silsha** [comment]
I've just submitted a PR (#4) which updates the `id`/`gid` fields in the sync_from_asana task. Apart from that, everything seems to work well.

**Comment by sbywater** [comment]
v1.3.0 includes a migration that adds a gid field to the relevant models and copies data from remote_id to this field. Please let me know if you find any further problems with this project and custom fields.

**Comment by silsha** [comment]
Thank you, the id/gid problem seems solved. 👍
