### ISSUE TITLE
Additional story resource_subtypes

### ISSUE THREAD

**Issue by silsha** [sbywater/django-asana#10]
Here are two more story `ressource_subtype`s I encountered:

* `dependency_marked_complete`
* `all_dependencies_marked_complete`

Both exceed the `max_length`of 24.

https://github.com/sbywater/django-asana/blob/b8aba1f262077912e9c26c050c3bd01903c5f9b6/djasana/models.py#L193-L216

**Comment by sbywater** [comment]
Excellent, thank you. I will add them with a migration to expand the field.

**Comment by silsha** [comment]
Just checked my database and found some more missing story subtypes (ready to paste):
```
('added_to_tag'), _('added to tag')
('added_to_task'), _('added to task')
('attachment_added'), _('attachment added')
('attachment_liked'), _('attachment liked')
('comment_liked'), _('comment liked')
('dependency_added'), _('dependency added')
('dependency_due_date_changed'), _('dependency due date changed')
('dependency_marked_incomplete'), _('dependency_marked incomplete')
('dependency_removed'), _('dependency removed')
('dependent_added'), _('dependent added')
('dependent_removed'), _('dependent removed')
('duplicate_merged'), _('duplicate merged')
('duplicated'), _('duplicated')
('enum_custom_field_changed'), _('enum custom field changed')
('marked_duplicate'), _('marked duplicate')
('marked_incomplete'), _('marked incomplete')
('number_custom_field_changed'), _('number custom field changed')
('removed_from_project'), _('removed from project')
('removed_from_tag'), _('removed from tag')
('removed_from_task'), _('removed from task')
('section_changed'), _('section changed')
('starting_today'), _('starting today')
('unassigned'), _('unassigned')
```

**Comment by sbywater** [comment]
To check for completeness (at least as far as we have), please try this:

`[s for s in Story.objects.distinct().values_list('resource_subtype', flat=True)]`

And feel free to submit a patch for this, if you'd like, or I can add it.

**Comment by silsha** [comment]
Sure, I can send a PR tomorrow, just have to clean up my workaround mess. 😉 

For documentation, this is the output:
`['added_to_project', 'assigned', 'due_date_changed', 'marked_complete', 'notes_changed', 'name_changed', 'attachment_added', 'comment_added', 'duplicated', 'dependent_added', 'dependency_added', 'dependency_marked_complete', 'all_dependencies_marked_complete', 'section_changed', 'follower_added', 'marked_today', 'number_custom_field_changed', 'dependency_due_date_changed', 'unassigned', 'comment_liked', 'marked_incomplete', 'enum_custom_field_changed', 'added_to_task', 'attachment_liked', 'marked_duplicate', 'duplicate_merged', 'liked', 'due_today', 'starting_today', 'removed_from_task', 'added_to_tag', 'removed_from_project', 'removed_from_tag', 'dependency_marked_incomplete', 'dependent_removed', 'dependency_removed']`
