### ISSUE TITLE
A dependency of this project (django-braces) has a bug that breaks the pip install routine

### ISSUE THREAD

**Issue by viktor-yunenko** [sbywater/django-asana#14]
It's resolvable by avoiding the latest release `django-braces < 1.14`.

The issue in django-braces - https://github.com/brack3t/django-braces/issues/261

**Comment by sbywater** [comment]
This looks good to go. It is bundled with other changes that need work in your request so it will wait for them. Generally, I would prefer one merge request per issue as it makes it easier to maintain, but these are straight forward. Thank you for your contribution!

**Comment by sbywater** [comment]
This has now been pulled into master and tagged version 1.4.5. Thanks again for the contribution.
