### ISSUE TITLE
Asana added a new field for CustomField - `has_notifications_enabled` - now the custom fields export raises an error

### ISSUE THREAD

**Issue by viktor-yunenko** [sbywater/django-asana#15]
In djsana.utils.sync_custom_fields function all the fields are read as a dict, but `has_notifications_enabled` field isn't present in CustomField model, hence Django returns a FieldError.

```
Invalid field name(s) for model CustomField: 'has_notifications_enabled'.
```

P.S. - awesome project 👍

**Comment by viktor-yunenko** [comment]
I'll prepare an MR

**Comment by sbywater** [comment]
This looks good to go. It is bundled with other changes that need work in your request so it will wait for them.

**Comment by sbywater** [comment]
I've merged these commits into master. Thank you.
