### ISSUE TITLE
Missing model fields

### ISSUE THREAD

**Issue by silsha** [sbywater/django-asana#5]
Some fields are missing from the models:

- **CustomField**
  - `resource_subtype`
  - `resource_type`
- **CustomFieldSettings**
  - `resource_type`
- **Tag**
  - `color`
  - `created_at`
  - `followers`
  - `notes`
  - `workspace`

As a workaround I've added the missing CustomField and CustomFieldSetting items as CharField, which seems to work. Since we don’t use tags, I've excluded the model from importing.

**Comment by sbywater** [comment]
Thank you. These are all added now in v1.3.3.
