### ISSUE TITLE
current_status of Project is invalid

### ISSUE THREAD

**Issue by silsha** [sbywater/django-asana#7]
The `current_status` field of the `Project` class currently references the task’s `STATUS_CHOICES` which leads to an error when importing projects with a status.

https://github.com/sbywater/django-asana/blob/fe4f5c3225a9910af748acea2473c00dec9c4632/djasana/models.py#L135

But it looks like you've already prepared the `ProjectStatus` class:
https://github.com/sbywater/django-asana/blob/fe4f5c3225a9910af748acea2473c00dec9c4632/djasana/models.py#L158-L174

**Comment by sbywater** [comment]
I do not understand how to create the error you see. Please provide code demonstrating the error.

**Comment by silsha** [comment]
It’s not possible to recreate this with a free account. With premium you can set a ProjectStatus (https://asana.com/developers/api-reference/project_statuses) which contains the fields you already created in the `ProjectStatus` class.

Currently you can only select the options from `STATUS_CHOICES` as `current_status` which is meant for tasks, not for projects.

I hope this helps. If not, just ask. :)

**Comment by sbywater** [comment]
Got it. Project.current_status needs to be a ForeignKey to ProjectStatus, not a CharField with choices. I will make this change.

**Comment by sbywater** [comment]
This is fixed now in 87127be5490da31254f8263ae83b27e45a48b64a tagged v1.3.6.
