### ISSUE TITLE
Invalid field name(s) for model CustomFieldSettings: 'parent'

### ISSUE THREAD

**Issue by silsha** [sbywater/django-asana#9]
Got this error when trying to sync with asana:
```
django.core.exceptions.FieldError: Invalid field name(s) for model CustomFieldSettings: 'parent'.
```

The field doesn’t seem to be documented: https://asana.com/developers/api-reference/custom_field_settings
As a workaround, I've added `parent` as CharField to the model. It references a project: 
```
{'id': 123456, 'gid': '123456', 'name': 'PROJECT NAME', 'resource_type': 'project'}
```

**Comment by sbywater** [comment]
This could be something that they are rolling out that hasn't hit my instance yet, or it could be something in the works that was mistakenly released early and then pulled back (that was the case with Attachment.type). I'll be on the lookout for this error on my end, or further reports from others, and if so will add a migration for it.

**Comment by sbywater** [comment]
Closing this issue as it has not materialized, and latest version prevents this kind of failure going forward.
